title: Intro to Git Training
description: Hands-on Git & GitLab workshop

# GitHub Pages URLs (project site)
url: "https://taylorpaisie.github.io"   # no trailing slash
baseurl: "/intro-to-git-training"       # repo name, leading slash

# Theme
remote_theme: andrewbanchich/forty-jekyll-theme

# GitHub Pages-required plugin for remote themes
plugins:
  - jekyll-remote-theme
