title: Intro to Git Training
description: Hands-on Git & GitLab workshop

# GitHub Pages URLs (project site)
url: "https://taylorpaisie.github.io"   # no trailing slash
baseurl: "/intro-to-git-training"       # repo name, leading slash

# Theme
remote_theme: mmistakes/minimal-mistakes

# GitHub Pages-required plugin for remote themes
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Minimal Mistakes options
minimal_mistakes_skin: "dark"

# Site Author
author:
  name: Taylor Paisie
  bio: "Git Training & DevOps"

# Site Footer
footer:
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: "https://github.com/taylorpaisie"

# Collections: lessons
collections:
  lessons:
    output: true
    permalink: /:collection/:name

# Sidebar navigation
sidebar:
  nav: "lessons"

# Navigation
navigation:
  lessons:
    - title: Lessons
      children:
        - title: Windows Setup
          url: /lessons/00_windows_setup/
        - title: Getting Set Up
          url: /lessons/01_intro/
        - title: Local Commits
          url: /lessons/02_local_commits/
        - title: Ignoring Things
          url: /lessons/03_ignoring_things/
        - title: Remotes (GitLab)
          url: /lessons/04_remotes_github/
        - title: Branching & MRs
          url: /lessons/05_branching_prs/
        - title: Merge Conflicts
          url: /lessons/06_merge_conflicts/
